# .goreleaser.yaml
# Configuration file for GoReleaser (The release automation tool)

version: 2

project_name: quick-share

# Commands to run before the build process starts
before:
  hooks:
    # Ensure dependencies are clean and up-to-date
    - go mod tidy

# Archive configuration (Compressing binaries into zip/tar.gz)
archives:
  - format: tar.gz
    # Use ZIP format for Windows (easier for users to extract)
    format_overrides:
      - goos: windows
        format: zip
    
    # Naming convention for the downloaded files
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

# Generate checksum file (SHA256) for security verification
checksum:
  name_template: 'checksums.txt'

# Snapshot configuration (for testing builds locally)
snapshot:
  name_template: "{{ .Tag }}-next"

# Changelog generation configuration
changelog:
  sort: asc
  filters:
    # Exclude commit messages that don't affect the user (docs, tests, etc.)
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'

# Release configuration (Publishing to GitHub, GitLab, etc.)
release:
  github:
    owner: firrthecreator
    name: quick-share
  draft: false
  prerelease: auto
  mode: keep-existing
