# .goreleaser.yaml
# Configuration file for GoReleaser (The release automation tool)

version: 2

project_name: quick-share

# Commands to run before the build process starts
before:
  hooks:
    # Ensure dependencies are clean and up-to-date
    - go mod tidy

builds:
  - main: ./cmd/quick-share/main.go
    binary: quick-share
    
    # Disable CGO to ensure the binary is statically linked (runs on any machine without dependencies)
    env:
      - CGO_ENABLED=0
    
    # Target Operating Systems
    goos:
      - linux
      - windows
      - darwin # macOS
    
    # Target Architectures
    goarch:
      - amd64 # Standard Intel/AMD processors
      - arm64 # Apple Silicon (M1/M2) & Linux ARM
    
    # Exclude specific combinations that are rarely used/problematic
    ignore:
      - goos: windows
        goarch: arm64

# Archive configuration (Compressing binaries into zip/tar.gz)
archives:
  - format: tar.gz
    # Use ZIP format for Windows (easier for users to extract)
    format_overrides:
      - goos: windows
        format: zip
    
    # Naming convention for the downloaded files
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}

# Generate checksum file (SHA256) for security verification
checksum:
  name_template: 'checksums.txt'

# Snapshot configuration (for testing builds locally)
snapshot:
  name_template: "{{ .Tag }}-next"

# Changelog generation configuration
changelog:
  sort: asc
  filters:
    # Exclude commit messages that don't affect the user (docs, tests, etc.)
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      